name: solari
description: "Accompanying mobile application for Solari smart glasses."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.0
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  file_picker: ^10.3.10
  path: ^1.9.0
  record: ^6.2.0
  path_provider: ^2.1.5
  cactus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true